services:
  app:
    image: phonebook-front
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend/:/usr/src/phonebook
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api
    container_name: phonebook-front

  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./backend/mongo_data:/data/db
  server:
    image: phonebook-back
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend/:/usr/src/phonebook

    environment:
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - mongo
    container_name: phonebook-back

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: phonebook-reverse-proxy-prod
    depends_on:
      - app
      - server
